pybo/urls.py
from django.urls import path
from .views import answer_views, base_views, question_views, comment_views, vote_views

app_name = 'pybo' # 네임 스페이스 지정 

urlpatterns = [
    # base_views
    path("", base_views.index, name='index'), # "pybo/" URL은 views.index함수와 연결
    path("<int:question_id>/",  base_views.detail, name='detail'),  # "pybo/{question_id}/" URL은 views.detail함수와 연결
    #answer_views
    path("answer/create/<int:question_id>/", answer_views.answer_create , name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"), # answer_id를 answer_modify에 넘겨줌 
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"), # answer_id를 answer_delete에 넘겨줌 
    #question_views
    path("question/create/", question_views.question_create , name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name='question_modify'), # question_id를 question_modify에 넘겨줌 
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"), # question_id를 question_delete에 넘겨줌 
    # comment_views
    path("comment/create/question/<int:question_id>/", comment_views.comment_create_question, name="comment_create_question"),
    path("comment/modify/question/<int:comment_id>/", comment_views.comment_modify_question, name="comment_modify_question"),
    path("comment/delete/question/<int:comment_id>/", comment_views.comment_delete_question, name="comment_delete_question"),
    path("comment/create/answer/<int:answer_id>/", comment_views.comment_create_answer, name="comment_create_answer"),
    path("comment/modify/answer/<int:comment_id>/", comment_views.comment_modify_answer, name="comment_modify_answer"),
    path("comment/delete/answer/<int:comment_id>/", comment_views.comment_delete_answer, name="comment_delete_answer"),
    # vote_views
    path("vote/question/<int:question_id>/", vote_views.vote_question , name="vote_question"), 
    path("vote/answer/<int:answer_id>/", vote_views.vote_answer , name="vote_answer"),
]  

pybo/models.py
from django.db import models # models는 Django에서 데이터베이스 테이블을 정의하고 관리하는 데 사용되는 모듈
from django.contrib.auth.models import User

# Question 클래스는 models.Model을 상속
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    voter = models.ManyToManyField(User, related_name='voter_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modified_date = models.DateTimeField(null=True, blank=True)

    # 모델 데이터 조회시 속성값 보여주기 위한 코드
    def __str__(self):
	    return self.subject #객체의 subject 속성 반환

# Answer 클래스는 models.Model을 상속
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    voter = models.ManyToManyField(User, related_name='voter_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField() 
    modified_date = models.DateTimeField(null=True, blank=True)


# Comment 클래스는 models.Model을 상속
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField() 
    modified_date = models.DateTimeField(null=True, blank=True)
    # 질문 또는 답변에 질문이 달릴거임, 그러므로 질문과 답변 필드 모두 null=True, blank=True로 설정 
        # 질문에 달린 댓글에 대해서는 답변 필드는 비어있고, 
        # 답변에 달린 댓글에 대해서는 질문 필드는 비어있고, 
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404,redirect, resolve_url #  render는 HTML 템플릿을 렌더링 모듈
from django.utils import timezone
from django.contrib import messages # 오류를 임의로 발생시키고자 하는 경우 사용(넌필드 오류에 해당당)
from django.contrib.auth.decorators import login_required

from ..models import Question, Answer
from ..forms import AnswerForm

 
@login_required(login_url='common:login') #함수 실행 전, 로그인 여부 검사
def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    # 질문 ID에 해당하는 Question 객체를 가져오거나 없으면 404 오류 반환
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST': # 사용자가 제출했을 경우
        form = AnswerForm(request.POST) #제출한 폼 내용 
        if form.is_valid():
            answer = form.save(commit=False) # commit=False는 임시 저장을 의미
            answer.author = request.user #현재 로그인한 계정의 User객체
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect( '{}#answer_{}'.format( resolve_url( 'pybo:detail', question_id=question.id ), answer.id ) )
    else: #get일 경우 # 사용자가 폼 요청했을 경우 
        form = AnswerForm()
    context = {'question':question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)



@login_required(login_url='common:login') # 로그인이 필요한 뷰
def answer_modify(request, answer_id):
    '''
    pybo 답변 수정
    '''
    answer = get_object_or_404(Answer, pk=answer_id)

    # 현재 user가 작성자 아닌 경우
    if(request.user != answer.author):
        messages.error(request, '수정권한이 없습니다.')
        redirect('pybo:detail', question_id=answer.question.id)

    # 현재 user가 작성자인 경우
    if request.method =='POST': #폼을 제출한 경우 
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False) #임시 저장
            answer.author = request.user
            answer.modified_date = timezone.now()
            answer = form.save()#DB에 반영
            return redirect( '{}#answer_{}'.format( resolve_url( 'pybo:detail', question_id=answer.question.id ), answer.id) )
    else: #GET#폼을 요청한 경우 
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form': form }
    return render(request, 'pybo/answer_form.html', context)




@login_required(login_url='common:login') # 로그인이 필요한 뷰
def answer_delete(request, answer_id):
    '''
    pybo 답변 삭제 
    '''
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id) 

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404,redirect #  render는 HTML 템플릿을 렌더링 모듈
from django.db.models import Q, Count

from ..models import Question

def index(request): # request는 장고에 의해 자동으으로 전달되는  HTTP 요청 객체임  
    """
    pybo 목록 출력
    """
 
    # 입력 인자
    page = request.GET.get('page', '1')  # 페이지 # /pybo/?page=1
    kw = request.GET.get('kw', '')       # 검색어
    so = request.GET.get('so', 'recent') # 정렬 기준

    # 정렬
    if so == 'recommend':
        # Question 객체에서 'voter' 필드의 개수를 세고, 'num_voter'로 임시 필드를 추가하여, 정렬에 활용
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date') # (-)역순 리스트
    elif so == 'popular':
        # Question 객체에서 'answer' 필드의 개수를 세고, 'num_answer'로 임시 필드를 추가하여, 정렬에 활용
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else: # so == 'recent'
        question_list = Question.objects.order_by('-create_date') #(-)역순 리스트

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw)|                   # 제목 검색
            Q(content__icontains=kw)|                   # 내용 검색
            Q(author__username__icontains=kw)|           # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)    # 답변 글쓴이 검색
        ).distinct()

    # 페이징 처리 
    paginator = Paginator(question_list, 10) #question_list를 페이징 객체 Paginator로 변환 # 페이지당 10개씩 보여 주기 
    page_obj = paginator.get_page(page)
    
    context = {'question_list': page_obj, 'page':page, 'kw':kw , 'so':so} #조회한 데이터 context변수에 저장 # key:value
    return render(request, 'pybo/question_list.html', context) # 템플릿(pybo/question_list.html)을 렌더링하여 HTTP 응답을 생성





def detail(request, question_id): # question_id는 URL에 있던 question_id임
    """
    pybo 내용 출력
    """
    # pk(primary key == id)에 해당하는 데이터가 없으면 오류 대신, 404페이지
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.shortcuts import render, get_object_or_404,redirect, resolve_url #  render는 HTML 템플릿을 렌더링 모듈
from django.utils import timezone
from django.contrib import messages # 오류를 임의로 발생시키고자 하는 경우 사용(넌필드 오류에 해당당)
from django.contrib.auth.decorators import login_required

from ..models import Question, Answer, Comment
from ..forms import CommentForm


@login_required(login_url='common:login') # 로그인이 필요한 뷰
def comment_create_question(request, question_id):
    '''
    pybo 질문 댓글 등록
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST": #질문 등록 폼 제출 
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=question.id), comment.id))
    else: #GET #질문 등록 폼 요청
        form = CommentForm()
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)





@login_required(login_url='common:login') # 로그인이 필요한 뷰
def comment_modify_question(request, comment_id):
    '''
    pybo 질문 댓글 수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    
    if request.method == "POST": # 폼 제출한 경우 
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modified_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else: #GET # 폼 요청한 경우 
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html',context)





@login_required(login_url='common:login') # 로그인이 필요한 뷰
def comment_delete_question(request, comment_id):
    '''
    pybo 질문 댓글 삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)




@login_required(login_url='common:login') # 로그인이 필요한 뷰
def comment_create_answer(request, answer_id):
    '''
    pybo 답변 댓글 등록
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST": #질문 등록 폼 제출 
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else: #GET #질문 등록 폼 요청
        form = CommentForm()
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)





@login_required(login_url='common:login') # 로그인이 필요한 뷰
def comment_modify_answer(request, comment_id):
    '''
    pybo 답변 댓글 수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    
    if request.method == "POST": # 폼 제출한 경우 
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modified_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id),comment.id))
    else: #GET # 폼 요청한 경우 
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html',context)





@login_required(login_url='common:login') # 로그인이 필요한 뷰
def comment_delete_answer(request, comment_id):
    '''
    pybo 답변 댓글 삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.shortcuts import render, get_object_or_404,redirect #  render는 HTML 템플릿을 렌더링 모듈
from django.contrib import messages # 오류를 임의로 발생시키고자 하는 경우 사용(넌필드 오류에 해당당)
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from ..models import Question
from ..forms import QuestionForm



@login_required(login_url='common:login') #함수 실행 전, 로그인 여부 검사
def question_create(request):
    """
    pybo 질문 등록 
    """
    if request.method == 'POST': # 사용자가 폼을 제출한 경우
        form = QuestionForm(request.POST)
        if form.is_valid(): # 폼의 입력 데이터가 유효한지 검사
            question = form.save(commit=False) # commit=False는 임시 저장을 의미 
            question.author = request.user #현재 로그인한 계정의 User객체
            question.create_date = timezone.now()
            question.save() # 실제 저장
            return redirect('pybo:index') #질문 등록이 완료된 후, 질문 목록 페이지로 이동
    else:
        form = QuestionForm() # get인 경우 호출 # 즉, 폼을 요청할 경우 실행

    context = {'form':form}
    return render(request, 'pybo/question_form.html', context) # context를 전달하여, form 요소 생성에 사용할거임 
 





@login_required(login_url='common:login') # 로그인이 필요한 뷰
def question_modify(request, question_id):
    '''
    pybo 질문 수정 
    ''' 
    # question_id에 해당하는 Question 객체 가져오기, 없으면 404 오류 반환
    question = get_object_or_404(Question, pk=question_id)
    
    # 현재 user가 작성자가 아닌 경우
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)

    # 현재 user가 작성자인 경우
    if request.method == "POST": # 폼 제출한 경우 
        # instance=question 통해, 사용자가 제출한 데이터를 기존 question 객체에 채워넣기 
        form = QuestionForm(request.POST, instance=question)  
        if form.is_valid():
            question = form.save(commit=False) 
            question.author = request.user # 보안과 데이터 무결성을 유지하기 위해
            question.modified_date = timezone.now()
            question.save() # 저장 (DB 반영)
            return redirect('pybo:detail', question_id=question.id)
    else: # GET # 폼 요청한 경우'    
        # instance=question 통해, 사용자가 제출한 데이터를 기존 question 객체 상태에서 시작
        # 기존 질문 데이터를 채운 상태로 폼 생성
        form = QuestionForm(instance=question) # 폼 생성
        
    # 템플릿에 전달할 데이터 설정
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)




@login_required(login_url='common:login') # 로그인이 필요한 뷰
def question_delete(request, question_id):
    '''
    pybo 질문 삭제
    '''
    question = get_object_or_404(Question, pk=question_id) #Question 테이블에서 pk=question_id인 데이터 찾아오기 

    # 현재 user가 작성자 아닌 경우
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    # 현재 user가 작성자인 경우
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.shortcuts import get_object_or_404,redirect #  render는 HTML 템플릿을 렌더링 모듈
from django.contrib import messages # 오류를 임의로 발생시키고자 하는 경우 사용(넌필드 오류에 해당당)
from django.contrib.auth.decorators import login_required

from ..models import Question, Answer


@login_required(login_url='common:login') #함수 실행 전, 로그인 여부 검사
def vote_question(request, question_id):
    '''
    pybo 질문 추천 등록 
    '''
    question = get_object_or_404(Question, pk=question_id)
    
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)



@login_required(login_url='common:login') #함수 실행 전, 로그인 여부 검사
def vote_answer(request, answer_id):
    '''
    pybo 답변 추천 등록 
    '''
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}

        {% include "form_errors.html" %}

        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                row="10">{{form.content.value|default_if_none:''}}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
<!-- HTML의 기본 구조를 정의한 base.html을 상속 받기 -->
{% extends 'base.html' %}
<!-- 마크다운 함수 로드 -->
{% load pybo_filter %}

<!-- 기본 템플릿 안에 삽입도리 내용 Strat -->
{% block content %}
    <div class="container my-3">
        <!-- 사용자 오류 표시 -->
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{message.tags}}</strong>
            <ul><li>{{message.message}}</li></ul>
        {% endfor %}
        </div>
        {% endif %}
 
        <!-- Question -->
        <h2 class="border-bottom py-2">{{question.subject}}</h2>
        
        <div class="row my-3">
            <!-- 추천 영역 -->
            <div class="col-1">
                <div class="bg-ligth text-center p-3 border font-weight-boder mb-1">{{question.voter.count}}</div>
                <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
                    class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            </div>
            <!-- 질문 영역 -->
             <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <!-- 질문 내용 -->
                        <div class="card-text">
                            {{question.content|mark}}
                        </div>
        
                        <!-- 수정일자 & 질문 작성자명 & 생성일자 -->
                        <div class="d-flex justify-content-end">
                            <!-- 수정일자 -->
                            {% if question.modified_date %}
                            <div class="badge badge-light p-2 text-left mx-3">
                                <div class="mb-2">modified at</div>
                                <div>{{question.modified_date}}</div>
                            </div>
                            {% endif %}
                            <!-- 질문 작성자명 & 생성일자 -->
                            <div class="badge badge-light p-2 text-left">
                                <div class="mb-2">{{question.author.username}}</div>
                                <div>{{question.create_date}}</div>
                            </div>
                        </div>
                        <!-- 질문 수정 & 삭제 버튼 -->
                        {% if request.user == question.author %}
                        <div class="my-3">
                            <a href="{% url 'pybo:question_modify' question.id %}" 
                                class="btn btn-sm btn-outline-secondary">수정</a>
                            <!-- data-uri 사용 통해, 삭제 확인 팝업을 띄우고 페이지를 이동하기 위함 -->
                            <a href="#" class="delete btn btn-sm btn-outline-secondary" 
                                data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                        </div>
                        {% endif %}
        
                        <!-- 질문 댓글 -->
                        {% if question.comment_set.count > 0 %}
                        <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                            <a name="comment_{{comment.id}}"></a> <!-- 스크롤 위치 -->
                            <div class="comment py-2 text-muted">
                                <!-- 질문댓글 내용 -->
                                <span style="white-space: pre-line;">{{ comment.content }}</span>
                                <!-- 질문댓글 정보 -->
                                <span>
                                    - {{comment.author}}, {{comment.create_date}}
                                    {% if comment.modified_date %}
                                    (수정:{{comment.modified_date}})
                                    {% endif %}
                                </span>
                                <!-- 질문댓글 수정 & 삭제 버튼 -->
                                {% if request.user == comment.author %}
                                <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
                                <a href="#" class="small delete"
                                    data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
                                {% endif %}
                            </div>
                        {% endfor %}
                        </div>
                        {% endif %}
        
                        <!-- 질문댓글 추가 기능 -->
                        <div class="mt-3">
                            <a href="{% url 'pybo:comment_create_question' question.id %}" class="small text-primary"><small>댓글 추가 ..</small></a>
                        </div>
        
                    </div>
                </div>
             </div>
        </div>


        <!-- Answer List -->
        <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
        {% for answer in question.answer_set.all %}
        <a name="answer_{{answer.id}}"></a> <!-- 스크롤 위치/ name은 유일해야 하므로, answer.id사용 -->
        <div class="row my-3">
            <!-- 추천 영역 -->
            <div class="col-1">
                <div class="badge-light text-center p-3 border font-weight-boder mb-1">
                    {{answer.voter.count}}
                </div>
                <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}"
                    class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            </div>

            <!-- 답변 영역 -->
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <!-- 답변 내용 -->
                        <div class="card-text" style="white-space: pre-line;">
                            {{answer.content|mark}}
                        </div>
                        <!-- 답변 수정일자 & 작성자명 & 작성일 -->
                        <div class="d-flex justify-content-end">
                            <!-- 수정일자 -->
                            {% if answer.modified_date %}
                            <div class="badge badge-light p-2 text-left mx-3">
                                <div class="mb-2">modified at</div>
                                <div>{{answer.modified_date}}</div>
                            </div>
                            {% endif %}
                            <!-- 질문 작성자명 & 생성일자 -->
                            <div class="badge badge-light p-2 text-left">
                                <div class="mb-2">{{answer.author.username}}</div>
                                <div>{{answer.create_date}}</div>
                            </div>
                        </div>
                        <!-- 답변 수정 & 삭제 버튼 -->
                        {% if request.user == answer.author %}
                        <div class="my-3">
                            <a href="{% url 'pybo:answer_modify' answer.id %}" 
                                class="btn btn-sm btn-outline-secondary">수정</a>
                            <!-- data-uri 사용 통해, 삭제 확인 팝업을 띄우고 페이지를 이동하기 위함 -->
                            <a href="#" class="delete btn btn-sm btn-outline-secondary" 
                                data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                        </div>
                        {% endif %}
    
                        <!-- 답변 댓글 -->
                        {% if answer.comment_set.count > 0 %}
                        <div class="mt-3">
                        {% for comment in answer.comment_set.all %} 
                            <a name="comment_{{comment.id}}"></a><!-- 스크롤 위치 -->
                            <div class="comment py-2 text-muted">
                                <!-- 답변댓글 내용 -->
                                <span style="white-space: pre-line;">{{ comment.content }}</span>
                                <!-- 답변댓글 정보 -->
                                <span>
                                    - {{comment.author}}, {{comment.create_date}}
                                    {% if comment.modified_date %}
                                    (수정:{{comment.modified_date}})
                                    {% endif %}
                                </span>
                                <!-- 답변댓글 수정 & 삭제 버튼 -->
                                {% if request.user == comment.author %}
                                <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>
                                <a href="#" class="small delete"
                                    data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                                {% endif %}
                            </div>
                        {% endfor %}
                        </div>
                        {% endif %}
                    
                        <!-- 답변댓글 추가 기능 -->
                        <div class="mt-3">
                            <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small text-primary"><small>댓글 추가 ..</small></a>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}

        <!-- Answer 등록 -->
        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}

            <!-- forms.is_valid()가 실패했을 경우 오류 표시 -->
            <!-- 오류 표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{field.label}}</strong>
                {{field.errors}}
                {% endif %}
            {% endfor%}
            </div>
            {% endif %}
            <!-- 오류 표시 End -->
             
            <div class="form-group">
                <!-- 로그인 상태에서만 입력 가능하게 조건 부여 -->
                <textarea name="content" id="content" 
                    {% if not user.is_authenticated %} disabled {% endif %}
                    class="form-control" rows="10"></textarea>
            </div>
            <input type="submit" value="답변 등록" class="btn btn-primary">
        </form>
    </div>
{% endblock%}
<!-- 기본 템플릿 안에 삽입도리 내용 End -->



<!-- 자바 스크립트 Start -->
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".delete").on('click', function(){ // 태그 중 delete 클래스 포함하는 경우
            if(confirm("정말로 삭제하시겠습니까?")){ //확인 누르면 
                location.href = $(this).data('uri');//data-uri로 이동하는 기능
            }
        });

        $(".recommend").on('click',function(){ // 태그 중 recommend 클래스 포함하는 경우 
            if(confirm("정말로 추천하시겠습니까?")){ //확인 누르면 
                location.href = $(this).data('uri');//data-uri로 이동하는 기능
            }
        });
    });
</script>
{% endblock%}
<!-- 자바 스크립트 End -->  