common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # django.contrib.auth앱의 LoginView 클래스를 활용했으므로 별도의 views.py 파일 수정 필요 없음 
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), 
    path('logout/', views.logout_view , name='logout'),
    path('signup/', views.signup, name='signup'),
]

pybo/urls.py
from django.urls import path
from .views import answer_views, base_views, question_views, comment_views, vote_views

app_name = 'pybo' # 네임 스페이스 지정 

urlpatterns = [
    # base_views
    path("", base_views.index, name='index'), # "pybo/" URL은 views.index함수와 연결
    path("<int:question_id>/",  base_views.detail, name='detail'),  # "pybo/{question_id}/" URL은 views.detail함수와 연결
    #answer_views
    path("answer/create/<int:question_id>/", answer_views.answer_create , name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"), # answer_id를 answer_modify에 넘겨줌 
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"), # answer_id를 answer_delete에 넘겨줌 
    #question_views
    path("question/create/", question_views.question_create , name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name='question_modify'), # question_id를 question_modify에 넘겨줌 
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"), # question_id를 question_delete에 넘겨줌 
    # comment_views
    path("comment/create/question/<int:question_id>/", comment_views.comment_create_question, name="comment_create_question"),
    path("comment/modify/question/<int:comment_id>/", comment_views.comment_modify_question, name="comment_modify_question"),
    path("comment/delete/question/<int:comment_id>/", comment_views.comment_delete_question, name="comment_delete_question"),
    path("comment/create/answer/<int:answer_id>/", comment_views.comment_create_answer, name="comment_create_answer"),
    path("comment/modify/answer/<int:comment_id>/", comment_views.comment_modify_answer, name="comment_modify_answer"),
    path("comment/delete/answer/<int:comment_id>/", comment_views.comment_delete_answer, name="comment_delete_answer"),
    # vote_views
    path("vote/question/<int:question_id>/", vote_views.vote_question , name="vote_question"), 
    path("vote/answer/<int:answer_id>/", vote_views.vote_answer , name="vote_answer"),
]  

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm): #UserCreationForm 상속 받음(username, password1, password2 속성)
    email = forms.EmailField(label="이메일") # email 속성 추가

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import redirect, render
from common.forms import UserForm


def logout_view(request):
    logout(request) # logout() 함수를 호출하여 세션을 종료
    return redirect('index')


def signup(request):
    '''
    회원가입
    '''
    if request.method == 'POST':  # POST 요청인 경우 (사용자가 회원가입 폼을 제출한 경우)
        form = UserForm(request.POST)  # UserForm 폼에 제출된 데이터를 담아옴
        if form.is_valid():  # 폼이 유효한지 검사 (유효성 검사)
            form.save()  # 유효하다면 폼을 저장 (회원가입을 완료)
            # 폼에서 사용자가 입력한 값 가져오기
            username = form.cleaned_data.get('username')  # username 필드 값
            raw_password = form.cleaned_data.get('password1')  # password1 필드 값 (비밀번호)
        
            ###회원가입 후 자동 로그인됨###
            # 사용자 인증 (입력한 username과 password로 로그인 시도)
            user = authenticate(username=username, password=raw_password)
            # 사용자 인증이 성공하면 로그인 처리
            login(request, user) 
            return redirect('index')# 로그인 후 index 페이지로 리다이렉트
    
    else: # GET 요청인 경우 (처음 회원가입 페이지를 열 때)
        form = UserForm()  # 빈 폼을 생성하여 사용자에게 전달
    
    # 회원가입 페이지 렌더링 (form 객체를 템플릿에 전달)
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 회원가입 링크 -->
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                또는 <a href="{% url 'common:signup'%}">계정을 만드세요.</a>
            </span>
        </div>
    </div>

    <!-- 로그인 입력 폼 -->
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- 로그인 성공 후 이동되는 URL -->
        <input type="hidden" name="next" value="{{next}}">
        {% include "form_errors.html" %}
        <!-- 아이디 입력 -->
        <div class="form-group">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{form.username.value|default_if_none:''}}">
        </div>
        <!-- 비밀번호 입력 -->
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{form.password.value|default_if_none:''}}">
        </div>
        <!-- 제출버튼 -->
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock%}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>

        <!-- 로그인 페이지 이동 링크 -->
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인하세요.</a></span>
        </div>
    </div>

    <form method="post" class="post-form">
        {% csrf_token %}

        <!-- 오류 표시를 위해 form_errors.html 삽입 -->
        {% include "form_errors.html" %}
        
        <!-- 회원 가입시 필요한 폼의 필드 입력 형식  -->
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{form.username.vlaue|default_if_none:''}}">
        </div>

        <div>
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{form.password1.vlaue|default_if_none:''}}">
        </div>

        <div>
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{form.password2.vlaue|default_if_none:''}}">
        </div>

        <div>
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{form.email.vlaue|default_if_none:''}}">
        </div>

        <button type="submit" class="bnt btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}