common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # django.contrib.auth앱의 LoginView 클래스를 활용했으므로 별도의 views.py 파일 수정 필요 없음 
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), 
    path('logout/', views.logout_view , name='logout'),
    path('signup/', views.signup, name='signup'),
]

pybo/urls.py
from django.urls import path
from .views import answer_views, base_views, question_views, comment_views, vote_views

app_name = 'pybo' # 네임 스페이스 지정 

urlpatterns = [
    # base_views
    path("", base_views.index, name='index'), # "pybo/" URL은 views.index함수와 연결
    path("<int:question_id>/",  base_views.detail, name='detail'),  # "pybo/{question_id}/" URL은 views.detail함수와 연결
    #answer_views
    path("answer/create/<int:question_id>/", answer_views.answer_create , name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"), # answer_id를 answer_modify에 넘겨줌 
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"), # answer_id를 answer_delete에 넘겨줌 
    #question_views
    path("question/create/", question_views.question_create , name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name='question_modify'), # question_id를 question_modify에 넘겨줌 
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"), # question_id를 question_delete에 넘겨줌 
    # comment_views
    path("comment/create/question/<int:question_id>/", comment_views.comment_create_question, name="comment_create_question"),
    path("comment/modify/question/<int:comment_id>/", comment_views.comment_modify_question, name="comment_modify_question"),
    path("comment/delete/question/<int:comment_id>/", comment_views.comment_delete_question, name="comment_delete_question"),
    path("comment/create/answer/<int:answer_id>/", comment_views.comment_create_answer, name="comment_create_answer"),
    path("comment/modify/answer/<int:comment_id>/", comment_views.comment_modify_answer, name="comment_modify_answer"),
    path("comment/delete/answer/<int:comment_id>/", comment_views.comment_delete_answer, name="comment_delete_answer"),
    # vote_views
    path("vote/question/<int:question_id>/", vote_views.vote_question , name="vote_question"), 
    path("vote/answer/<int:answer_id>/", vote_views.vote_answer , name="vote_answer"),
]  

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404,redirect #  render는 HTML 템플릿을 렌더링 모듈
from django.db.models import Q, Count

from ..models import Question

def index(request): # request는 장고에 의해 자동으으로 전달되는  HTTP 요청 객체임  
    """
    pybo 목록 출력
    """
 
    # 입력 인자
    page = request.GET.get('page', '1')  # 페이지 # /pybo/?page=1
    kw = request.GET.get('kw', '')       # 검색어
    so = request.GET.get('so', 'recent') # 정렬 기준

    # 정렬
    if so == 'recommend':
        # Question 객체에서 'voter' 필드의 개수를 세고, 'num_voter'로 임시 필드를 추가하여, 정렬에 활용
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date') # (-)역순 리스트
    elif so == 'popular':
        # Question 객체에서 'answer' 필드의 개수를 세고, 'num_answer'로 임시 필드를 추가하여, 정렬에 활용
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else: # so == 'recent'
        question_list = Question.objects.order_by('-create_date') #(-)역순 리스트

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw)|                   # 제목 검색
            Q(content__icontains=kw)|                   # 내용 검색
            Q(author__username__icontains=kw)|           # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)    # 답변 글쓴이 검색
        ).distinct()

    # 페이징 처리 
    paginator = Paginator(question_list, 10) #question_list를 페이징 객체 Paginator로 변환 # 페이지당 10개씩 보여 주기 
    page_obj = paginator.get_page(page)
    
    context = {'question_list': page_obj, 'page':page, 'kw':kw , 'so':so} #조회한 데이터 context변수에 저장 # key:value
    return render(request, 'pybo/question_list.html', context) # 템플릿(pybo/question_list.html)을 렌더링하여 HTTP 응답을 생성





def detail(request, question_id): # question_id는 URL에 있던 question_id임
    """
    pybo 내용 출력
    """
    # pk(primary key == id)에 해당하는 데이터가 없으면 오류 대신, 404페이지
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- 메타 태그 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 부트스트랩 -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"></link>
    <!-- pybo css -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"></link>
    <title>파이보</title>
</head>

<!-- 내비게이션 바 -->
{% include "navbar.html" %}

<body>
<!-- 기본 템플릿 안에 삽입도리 내용 Strat -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입도리 내용 End -->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.7.1.min.js' %}"></script>
<!-- 부트스트랩 JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바 스크립트 Start -->
{% block script %}
{% endblock%}
<!-- 자바 스크립트 End -->

</body>
</html> 

templates/form_errors.html
<!-- 에러가 있다면 로그인 실패 원인을 출력하는 로직직 -->
{% if form.errors %}
    {% for field in form %}
        <!-- 필드 오류(입력값이 누락되었거나 형식 안맞춘 경우 발생) 출력 -->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{field.label}}</strong>
                {{error}}
            </div>
        {% endfor %}
    {% endfor %}

    <!-- non_field 오류(입력값과 관계없이 발생) 출력 -->
    {% for error in form.non_field_errors %}  
        <div class="alert alert-danger">
            <strong>{{error}}</strong>
        </div>
    {%  endfor %}
{% endif %}

templates/navbar.html
<!-- 내비게이션 바 -->
<nav class="navbar navbar-extend-lg navbar-light bj-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
        data-target="#navbarNav" aria-controls="navbarNav" aria-extended="flase"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <!-- 만약 로그인 상태라면, 로그아웃 링크 -->
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}} (로그아웃)</a>
                <!-- 아직 로그인하지 않은 상태라면, 로그인 링크 -->
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>